CO2Cap: 0
CapacityReserveMargin: 0
EnergyShareRequirement: 0
MaxCapReq: 0
MethodofMorris: 0
MinCapReq: 0
ModelingToGenerateAlternativeIterations: 3
ModelingToGenerateAlternatives: 0
ModelingtoGenerateAlternativeSlack: 0.1
NetworkExpansion: 0
OperationalReserves: 0
OutputFullTimeSeries: 1
OverwriteResults: 0
ParameterScale: 1
PrintModel: 0
Solver: Gurobi
StorageLosses: 0
TimeDomainReduction: 0
TimeDomainReductionFolder: TDR_Results
Trans_Loss_Segments: 1
UCommit: 2
WriteShadowPrices: 1
