IterativelyAddPeriods: 1
ExtremePeriods:
  Wind:
    System:
      Absolute:
        Min: 0
        Max: 0
      Integral:
        Min: 0
        Max: 0
    Zone:
      Absolute:
        Min: 0
        Max: 0
      Integral:
        Min: 1
        Max: 0
  PV:
    System:
      Absolute:
        Min: 0
        Max: 0
      Integral:
        Min: 0
        Max: 0
    Zone:
      Absolute:
        Min: 0
        Max: 0
      Integral:
        Min: 1
        Max: 0
  Demand:
    System:
      Absolute:
        Min: 0
        Max: 1
      Integral:
        Min: 0
        Max: 0
    Zone:
      Absolute:
        Min: 0
        Max: 0
      Integral:
        Min: 0
        Max: 0
UseExtremePeriods: 1
MinPeriods: 5
MaxPeriods: 5
DemandWeight: 1
ClusterFuelPrices: 1
nReps: 100
MultiStageConcatenate: 0
Threshold: 0.05
TimestepsPerRepPeriod: 24
IterateMethod: "cluster"
ScalingMethod: "S"
ClusterMethod: "kmeans"
WeightTotal: 8760
